name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cnaude
main: com.cnaude.headmap.HMMain
commands:
    hmcreate:
        description: Create a map with a player's head as the picture.
        usage: /hmcreate [name]
permissions:
  'headmap.create':
    description: Gives player access to the the /hmcreate command.
    default: op
permissions:
  'headmap.face':
    description: Gives player permission to head map.
    default: true
permissions:
  'headmap.body':
    description: Gives player permission to craft a body map.
    default: true   